GitLab Runner Support
traderepublic/Cilicon pull request #4
Opened 2023-02-07 22:38 UTC by ast3150

**Adds support for GitLab Runner provisioning on hosted GitLab instances**

- Adds a `gitlab` provisioner option
- Adds a `GitLabRunnerProvisioner` and related types

The GitLab Runner Provisioner will automatically register a runner on a given self-hosted GitLab instance when the VM is started, and de-register the runner when the VM is shutdown.

### Usage

1. Set the provisioner to `gitlab` and provide the relevant configurations:
```
provisioner:
  type: gitlab
  config:
     name: "my-runner"
     url: "https://gitlab.yourcompany.net/"
     registrationToken: "your-runner-registration-token"
     tagList: "some-tags,comma-separated"
```
2. Provide the `gitlab-runner` binary in the VM bundle "Resources" folder
3. Set up the GitLab Runner binary in the `start.command` launch item. Example:
```
resources="/Volumes/My Shared Files/Resources/"

# Set up GitLab Runner
runner_exec_file="$resources/gitlab-runner-darwin-arm64"
token_file="$resources/RUNNER_TOKEN"
endpoint_file="$resources/RUNNER_ENDPOINT_URL"

sudo mkdir -p /usr/local/bin
sudo mv "$runner_exec_file" /usr/local/bin/gitlab-runner
sudo chmod +x /usr/local/bin/gitlab-runner

# Bypass Apple security measures: Can't be opened because Apple cannot check it for malicious software
sudo xattr -d com.apple.quarantine /usr/local/bin/gitlab-runner

# Run the Runner
token=$(cat "$token_file")
endpoint=$(cat "$endpoint_file")

/usr/local/bin/gitlab-runner run-single -u $endpoint -t $token --executor shell --env "FF_RESOLVE_FULL_TLS_CHAIN=1" --max-builds 1

# Shut down the VM after build is completed
sudo shutdown -r now
```

2023-02-08 13:40 UTC, Marcocanc requested changes
Thanks for the contribution! 🚀 
Could you please also do the following:
- [ ] Add the script to the `VM Resources` folder
- [ ] Mention The GitLab Provisioner in the Readme

2023-02-08 13:40 UTC, Marcocanc commented on Cilicon/Config/GitLabProvisionerConfig.swift
> +        case executablePath
I guess this is a leftover from copying the contents of the `ProcessProvisioner`?

2023-02-08 13:40 UTC, Marcocanc commented on Cilicon/Config/GitLabProvisionerConfig.swift
> +    }
This whole part can be omitted which will fall back to the synthesized decoder init. Other types in the project implement the initializer due to polymorphism or custom requirements (e.g. `standardizingPath` on local paths)

2023-02-08 13:40 UTC, Marcocanc commented on Cilicon/Config/ProvisionerConfig.swift
> +            let config = try container.decode(GitLabProvisionerConfig.self, forKey: .config)
Nitpick, but would be nice to be consistent in terms of casing.
Either GitLab (`GitLabProvisioner` and `.gitLab`) or Gitlab  (`GitlabProvisioner` and `.gitlab`):

2023-02-08 13:40 UTC, Marcocanc commented on Cilicon/Provisioner/GitLab Runner/GitLabService.swift
> +
Can we remove the header please?

2023-02-08 13:40 UTC, Marcocanc commented on Cilicon/Provisioner/GitLab Runner/GitLabService.swift
> +            case id, token
Can be omitted

2023-02-08 15:51 UTC, ast3150 commented on Cilicon/Config/ProvisionerConfig.swift
> +            let config = try container.decode(GitLabProvisionerConfig.self, forKey: .config)
Totally agree, I changed it to `Gitlab` to be consistent with the `GithubService` 

(GitHub and GitLab both technically use this capitalization but consistency is more important)

2023-02-09 08:53 UTC, Marcocanc approved these changes

2023-02-09 13:17 UTC, Marcocanc commented
We currently don't have automated tests for Cilicon. I will test that the rest still functions as expected soon and then merge + create a new release.

2023-03-07 09:43 UTC, merged