Pass config as launch argument to support different config file location
traderepublic/Cilicon pull request #58
Opened 2024-09-06 08:42 UTC by FabianBartels

This PR adds the functionality to change the configuration location.

How to use:
open /Applications/Cilicon.app --args -config-path /Users/<username>/<some-other-folder>/cilicon.yml

If no argument is set it will search for the regular default paths which are:
/Users/<username>/cilicon.yml
/Users/<username>/.cilicon.yml

2024-09-06 08:44 UTC, FabianBartels commented
Hi @Marcocanc, 
can you have a look on this PR :).

If you have questions or change requests, let me know. 
I'll answer and adjust accordingly.

2024-09-09 10:00 UTC, Marcocanc requested changes

2024-09-09 10:00 UTC, Marcocanc commented on Cilicon/Config/ConfigManager.swift
> +    static let fallbackConfig = ["/cilicon.yml", "/.cilicon.yml"]
Small nitpick. Let's name it `fallbackConfigPath`

2024-09-09 10:00 UTC, Marcocanc commented on Cilicon/Config/ConfigManager.swift
> +        }
Let's combine these two into a single guard statement as they throw the same error.

2024-09-10 10:49 UTC, FabianBartels commented on Cilicon/Config/ConfigManager.swift
> +    static let fallbackConfig = ["/cilicon.yml", "/.cilicon.yml"]
Done

2024-09-10 10:49 UTC, FabianBartels commented on Cilicon/Config/ConfigManager.swift
> +        }
Done

2024-09-10 10:54 UTC, FabianBartels commented
Hi @Marcocanc,
Thanks for having a look on my PR. I have adopted the change as requested :). 

I let the conversation resolving up to you. 

Cheers,
Fabian

2024-09-10 16:08 UTC, Marcocanc approved these changes

2024-09-10 16:09 UTC, merged

2024-09-10 16:09 UTC, Marcocanc commented
Thx for the contribution!